################################################################################
# Joshua C. Fjelstul, Ph.D.
# eutr R package
# automatically generated by the codebookr R package
################################################################################

#' Data on comments
#'
#' This dataset includes data on comments submitted by third-party member
#' states and institutions in reponse to proposed technical regulations
#' notified by member states (1988-2020). There is one observation per
#' comment. The dataset indicates the the member state or institution that
#' submitted the comment and the member state that notified the proposed
#' technical regulation to the Commission.
#'
#' @format A data frame with 13 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{notification_id}{String. An ID number that uniquely identifies the
#' notification in the format \code{TRIS:####:####:XX:N}, where the first set
#' of digits is the year of the notification, the second set of digits is the
#' notification number, and \code{XX} is the two-digit code assigned by the
#' Commission to the member state that notified the proposed technical
#' regulation.}
#' \item{notification_by_id}{Numeric. An ID number that uniquely identifies
#' the member state that notified the proposed technical regulation to the
#' Commission.}
#' \item{notification_by}{String. The name of the member state that notified
#' the proposed technical regulation to the Commission.}
#' \item{notification_by_code}{String. A multi-letter code assigned by the
#' Commission that uniquely identifies the member state that notified the
#' proposed technical regulation to the Commission.}
#' \item{start_date}{String. The date that the Commission opened the case.}
#' \item{start_year}{Numeric. The year that the Commission opened the case.}
#' \item{end_date}{String. The date that the Commission closed the case.}
#' \item{end_year}{Numeric. The year that the Commission closed the case.}
#' \item{comment_id}{String. An ID number that uniquely identifies the comment
#' in the format \code{TRIS:####:####:XX:C:YY}, where the first set of digits
#' is the year of the notification, the second set of digits is the
#' notification number, \code{XX} is the two-letter code assigned by the
#' Commission to the member state that notified the proposed technical
#' regulation, and \code{YY} is the multi-letter code assigned by the
#' Commission to the member state or institution that submitted the comment.}
#' \item{comment_by_id}{Numeric. An ID number that uniquely identifies the
#' member state or institution that submitted the comment to the Commission.}
#' \item{comment_by}{String. The name of the third-party member state or
#' institution that submitted the comment.}
#' \item{comment_by_code}{String. A multi-letter code assigned by the
#' Commission that uniquely identifies the member state or institution that
#' submitted the comment.}
#' }
"comments"

################################################################################
# end R script
################################################################################
