################################################################################
# Joshua C. Fjelstul, Ph.D.
# eutr R package
# automatically generated by the codebookr R package
################################################################################

#' Comment-level cross-sectional time-series data by submitter
#' 
#' This dataset includes aggregated data on the number of comments submitted
#' by each third-party member state or institution per year (cross-sectional
#' time-series data). There is one observation per third-party member state or
#' institution per year (1988-2020), excluding state-years where the state was
#' not a member of the Single Market.
#' 
#' @format A data frame with 6 variables:
#' \describe{
#' \item{key_id}{\code{numeric}. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{\code{numeric}. The year the member state or institution
#' submitted the comment.}
#' \item{comment_by_id}{\code{numeric}. An ID number that uniquely identifies
#' the member state or institution that submitted the comment to the
#' Commission.}
#' \item{comment_by}{\code{string}. The name of the third-party member state
#' or institution that submitted the comment.}
#' \item{comment_by_code}{\code{string}. A multi-letter code assigned by the
#' Commission that uniquely identifies the member state or institution that
#' submitted the comment.}
#' \item{count_comments}{\code{numeric}. A count of the number of comments
#' submitted by the third-party member state or institution.}
#' }
"comments_csts_s"

################################################################################
# end R script
################################################################################

