################################################################################
# Joshua C. Fjelstul, Ph.D.
# eutr R package
# automatically generated by the codebookr R package
################################################################################

#' Entity codes
#' 
#' This dataset includes data on the member states (including members of the
#' Single Market that are not members of the EU) and institutions that can
#' submit a comment or detailed opinion. There is one observation per entity.
#' The institutions that participate in the 2015/1535 procedure are the
#' European Commission and the European Free Trade Association (EFTA).
#' 
#' @format A data frame with 4 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{entity_id}{Numeric. An ID number that uniquely identifies the member
#' state or institution.}
#' \item{entity}{String. The name of the member state or institution that
#' submitted the opinion to the Commission.}
#' \item{entity_code}{String. A multi-letter code assigned by the Commission
#' that uniquely identifies the member state or institution.}
#' }
"entity_codes"

################################################################################
# end R script
################################################################################

