################################################################################
# Joshua C. Fjelstul, Ph.D.
# eutr R package
# automatically generated by the codebookr R package
################################################################################

#' TS data on notifictions
#' 
#' This dataset includes aggregated data on the number of notified technical
#' regulations per year (time-series data). There is one observation per year
#' (1988-2020).
#' 
#' @format A data frame with 3 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{Numeric. The year the member state notified the proposed
#' technical regulation to the Commission.}
#' \item{notification_by_id}{Numeric. An ID number that uniquely identifies
#' the member state that notified the proposed technical regulation to the
#' Commission.}
#' }
"notifications_ts"

################################################################################
# end R script
################################################################################

