################################################################################
# Joshua C. Fjelstul, Ph.D.
# eutr R package
# automatically generated by the codebookr R package
################################################################################

#' Notification-level data
#' 
#' This dataset include data on technical regulations proposed at the national
#' level by member states of the EU Single Market (including members of the
#' Single Market that are not members of the EU) that are notified to the
#' Commission under the 2015/1535 procedure. There is one observation per
#' notified technical regulation (1988-2020). The dataset includes information
#' on the start and end dates of the case, the member state that notified the
#' proposed technical regulation, which third-party member states or
#' institutions (if any) submitted comments and/or detailed opinions, and
#' whether the Commission submitted a comment and/or detailed opinion.
#' 
#' @format A data frame with 16 variables:
#' \describe{
#' \item{key_id}{\code{numeric}. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{notification_id}{\code{string}. An ID number that uniquely identifies
#' the notification in the format \code{TRIS:####:####:XX:N}, where the first
#' set of digits is the year of the notification, the second set of digits is
#' the notification number, and \code{XX} is the two-digit code assigned by
#' the Commission to the member state that notified the proposed technical
#' regulation.}
#' \item{notification_by_id}{\code{numeric}. An ID number that uniquely
#' identifies the member state that notified the proposed technical regulation
#' to the Commission.}
#' \item{notification_by}{\code{string}. The name of the member state that
#' notified the proposed technical regulation to the Commission.}
#' \item{notification_by_code}{\code{string}. A multi-letter code assigned by
#' the Commission that uniquely identifies the member state that notified the
#' proposed technical regulation to the Commission.}
#' \item{start_date}{\code{string}. The date that the Commission opened the
#' case.}
#' \item{start_year}{\code{numeric}. The year that the Commission opened the
#' case.}
#' \item{end_date}{\code{string}. The date that the Commission closed the
#' case.}
#' \item{end_year}{\code{numeric}. The year that the Commission closed the
#' case.}
#' \item{postponement}{\code{dummy}. A dummy variable indicating whether the
#' notified technical regulation was postponed. Coded \code{1} if the
#' technical regulation was postponed and \code{0} otherwise.}
#' \item{comments}{\code{string}. A list of the member states and institutions
#' that submitted comments with respect to the proposed technical regulation,
#' separated by commas. Coded \code{NA} if no member states or institutions
#' submitted opinions.}
#' \item{count_comments}{\code{numeric}. A count of the number of comments
#' submitted by the third-party member state or institution.}
#' \item{commission_comment}{\code{dummy}. A dummy variable indicating whether
#' the Commission submitted a comment with respect to the notified proposed
#' technical regulation. Coded \code{1} if the Commission submitted a comment
#' and \code{0} otherwise.}
#' \item{opinions}{\code{string}. A list of the member states and institutions
#' that submitted opinions with respect to the proposed technical regulation,
#' separated by commas. Coded \code{NA} if no member states or institutions
#' submitted opinions.}
#' \item{count_opinions}{\code{numeric}. A count of the number of opinions
#' submitted by the third-party member state or institution.}
#' \item{commission_opinion}{\code{dummy}. A dummy variable indicating whether
#' the Commission submitted an opinion with respect to the notified proposed
#' technical regulation. Coded \code{1} if the Commission submitted an opinion
#' and \code{0} otherwise.}
#' }
"notifications"

################################################################################
# end R script
################################################################################

