################################################################################
# Joshua C. Fjelstul, Ph.D.
# eutr R package
# automatically generated by the codebookr R package
################################################################################

#' Opinion-level cross-sectional time-series data by notifier
#' 
#' This dataset includes aggregated data on the number of detailed opinions
#' submitted against each notifying member state per year (cross-sectional
#' time-series data). There is one observation per notifying member state per
#' year (1988-2020), excluding state-years where the state was not a member of
#' the Single Market.
#' 
#' @format A data frame with 6 variables:
#' \describe{
#' \item{key_id}{\code{numeric}. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{\code{numeric}. The year the member state or institution
#' submitted the detailed opinion.}
#' \item{notification_by_id}{\code{numeric}. An ID number that uniquely
#' identifies the member state that notified the proposed technical regulation
#' to the Commission.}
#' \item{notification_by}{\code{string}. The name of the member state that
#' notified the proposed technical regulation to the Commission.}
#' \item{notification_by_code}{\code{string}. A multi-letter code assigned by
#' the Commission that uniquely identifies the member state that notified the
#' proposed technical regulation to the Commission.}
#' \item{count_opinions}{\code{numeric}. A count of the number of opinions
#' submitted by the third-party member state or institution.}
#' }
"opinions_csts_n"

################################################################################
# end R script
################################################################################

