################################################################################
# Joshua C. Fjelstul, Ph.D.
# eutr R package
# automatically generated by the codebookr R package
################################################################################

#' Network data on detailed opinions
#' 
#' This dataset includes network data on detailed opinions. Network data is
#' similar to directed dyad-year data except that it only includes directed
#' dyad-years with at least one detailed opinion. For every year, there is one
#' node per member state or institution that can submit a detailed opinion or
#' notify a proposed technical regulation (only member states). Links can only
#' exist between a third-party member state or institution that can submit a
#' detailed opinion and a member state that can notify a technical regulation.
#' There is a link between a third-party member state or institution and a
#' notifying member state if and only if the former submitted at least one
#' detailed opinion with respect to a technical regulation notified by the
#' latter. The weight of the edge is the number of detailed opinions
#' submitted. There is one observation per third-party member state or
#' institution per notifying member state per year (2002-2020), excluding
#' directed dyad-years where a state was not a member of the Single Market,
#' but only if count of comments is positive.
#' 
#' @format A data frame with 7 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{time}{Numeric. The time period, where \code{1988} is coded \code{1}.
#' }
#' \item{from_node_id}{Numeric. An ID number that uniquely identifies each
#' node (a member state or institution) that creates a link.}
#' \item{from_node}{String. The name of the member state or institution that
#' submitted the opinion to the Commission.}
#' \item{to_node_id}{Numeric. An ID number that uniquely identifies each node
#' (a member state) that receives a link.}
#' \item{to_node}{String. The name of the member state that notified the
#' technical regulation to the Commission.}
#' \item{edge_weight}{Numeric. The weight of the edge, which is the number of
#' opinions filed against the member state the notified the proposed technical
#' regulation.}
#' }
"opinions_net"

################################################################################
# end R script
################################################################################

